// Wait! The user says "there is no css on translated pages".
// Why is there no CSS? Because the `lang` attribute is `html lang={lang}`.
// And the CSS in `src/styles/global.css` or `BaseHead.astro` scopes things.
// In `BaseHead.astro`, the `data-theme` handles dark mode.
// Does the CSS missing mean the `<link rel="stylesheet">` generated by Vite is a relative path `href="_astro/index.css"` instead of `/astro-scholar/_astro/index.css`?
// If the page is in `dist/hi/index.html`, and `href` is `../_astro/index.css`, then it should work if it's relative.
// Let's check the generated `index.html` CSS link.
